[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "openzeppelin-contracts/=lib/openzeppelin-contracts/",
  "openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/",
  "forge-std/=lib/forge-std/src/",
]

# Build settings
solc = "0.8.29"
optimizer = true
optimizer_runs = 200
via_ir = false
bytecode_hash = "none"
gas_reports = ["ACMNToken"]
fuzz_runs = 512
invariant_runs = 512

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
