name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Show versions
        run: |
          forge --version
          solc --version || true

      - name: Format check
        run: forge fmt --check

      - name: Build
        run: forge build --sizes

      - name: Test (with gas report)
        run: forge test --gas-report | tee gas-report.txt

      - name: Upload gas report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gas-report
          path: gas-report.txt

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install solhint
        run: npm install -g solhint

      - name: Run solhint
        run: |
          solhint -V
          solhint "src/**/*.sol" "test/**/*.sol" "script/**/*.sol" || true
        continue-on-error: true

  slither:
    runs-on: ubuntu-latest
    needs: build-and-test
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Run Slither
        uses: crytic/slither-action@v0.4.0
        with:
          target: .
          sarif: true
          fail-on: medium

      - name: Upload SARIF to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
